version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # 配置文件
      - ./picture:/picture # 图片路径
  mongo-27017:
    image: mongo:latest
    container_name: mongo-27017
    restart: always
    ports:
      - 27017:27017
    command: mongod --replSet onss --oplogSize 128 --port 27017 # replSet 使用副本集功能
    environment:
      MONGODB_APPLICATION_DATABASE: test # 初始化DATABASE
  mongo-27018:
    image: mongo:latest
    container_name: mongo-27018
    restart: always
    ports:
      - 27018:27018
    command: mongod --replSet onss --oplogSize 128 --port 27018
    environment:
      MONGODB_APPLICATION_DATABASE: test
  mongo-init:
    image: mongo:latest
    depends_on:
      - mongo-27017
      - mongo-27018
    restart: on-failure:5
    command:
      - mongo
      - mongodb://192.168.103.184:27017/admin
      - --eval
      - 'rs.initiate({ _id: "onss", members: [{_id:0,host:"192.168.103.184:27017"},{_id:2,host:"192.168.103.184:27018"}]})' # 初始化副本集群
  store:
    image: "java:8"
    container_name: store
    restart: always
    depends_on:
      - mongo-27017
      - mongo-27018
      - nginx
    ports:
      - 8001:8001
    volumes:
      - /Users/wangchanghao/Desktop/work/onss/picture:/picture
      - /Users/wangchanghao/Desktop/work/onss/web/store/target/store-service-0.0.1-SNAPSHOT.jar:/onss/store-service-0.0.1-SNAPSHOT.jar
    entrypoint: ["java","-jar","/onss/store-service-0.0.1-SNAPSHOT.jar"]