version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # 配置文件
      - ./picture:/picture # 图片路径
  mongo-27117:
    image: mongo:latest
    container_name: mongo-27117
    restart: always
    ports:
      - 27117:27117
    command: mongod --replSet onss --oplogSize 128 --bind_ip 0.0.0.0 --port 27117 # replSet 使用副本集功能
    environment:
      MONGODB_APPLICATION_DATABASE: test # 初始化DATABASE
  mongo-27118:
    image: mongo:latest
    container_name: mongo-27118
    restart: always
    ports:
      - 27118:27118
    command: mongod --replSet onss --oplogSize 128 --bind_ip 0.0.0.0 --port 27118
    environment:
      MONGODB_APPLICATION_DATABASE: test
  mongo-184-init:
    image: mongo:latest
    depends_on:
      - mongo-27117
      - mongo-27118
    restart: on-failure:5
    command:
      - mongo
      - mongodb://192.168.103.184:27117/admin
      - --eval
      - 'rs.initiate({ _id: "onss", members: [{_id:0,host:"192.168.103.184:27117"},{_id:1,host:"192.168.103.184:27118"}]})' # 初始化副本集群