version: "3"                                   # compose-file的语法版本
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_VHOST=onss
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    restart: always
  nexus:
    container_name: nexus
    image: "sonatype/nexus3:latest"
    restart: always
    ports:
      - 8181:8181
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - /Users/wangchanghao/Desktop/work/onss/nginx/conf.d:/etc/nginx/conf.d
      - /Users/wangchanghao/Desktop/work/onss/picture:/picture
  mongo-27017:
    image: "mongo:latest"
    container_name: mongo-27017
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /Users/wangchanghao/Desktop/work/onss/mongodb/mongodb.key:/data/mongodb.key
    command: mongod --replSet mongos

  mongo-27018:
    image: "mongo:latest"
    container_name: mongo-27018
    restart: always
    ports:
      - 27018:27017
    volumes:
      - /Users/wangchanghao/Desktop/work/onss/mongodb/mongodb.key:/data/mongodb.key
    command: mongod --replSet mongos
  mongo-init:
    image: mongo:latest
    command:
      - mongo
      - mongodb://mongo-27018/admin
      - --eval
      - 'rs.initiate({ _id: "mongos", members: [{_id:1,host:"127.0.0.1:27017"},{_id:2,host:"127.0.0.1:27018"}]});rs.status()'
#  store:
#    image: "java:8"
#    container_name: store
#    restart: always
#    ports:
#      - 8001:8001
#    volumes:
#      - /Users/wangchanghao/Desktop/work/onss/picture:/picture
#      - /Users/wangchanghao/Desktop/work/onss/web/store/target/store-service-0.0.1-SNAPSHOT.jar:/onss/store-service-0.0.1-SNAPSHOT.jar
#    depends_on:
#      - nginx
#      - mongo
#    entrypoint: ["java","-jar","/onss/store-service-0.0.1-SNAPSHOT.jar"]

  nifi:
    container_name: nifi
    image: "apache/nifi:latest"
    ports:
      - 8080:8080
    restart: always