version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # 配置文件
      - ./picture:/picture # 图片路径
  mongo-27117:
    image: mongo:latest
    container_name: mongo-27117
    restart: always
    ports:
      - 27117:27117
    command: mongod --replSet onss --oplogSize 128 --bind_ip 0.0.0.0 --port 27117 # replSet 使用副本集功能
    environment:
      MONGODB_APPLICATION_DATABASE: test # 初始化DATABASE
  mongo-27118:
    image: mongo:latest
    container_name: mongo-27118
    restart: always
    ports:
      - 27118:27118
    command: mongod --replSet onss --oplogSize 128 --bind_ip 0.0.0.0 --port 27118
    environment:
      MONGODB_APPLICATION_DATABASE: test
  mongo-184-init:
    image: mongo:latest
    depends_on:
      - mongo-27117
      - mongo-27118
    restart: on-failure:5
    command:
      - mongo
      - mongodb://49.232.165.242:27117/admin
      - --eval
      - 'rs.initiate({ _id: "onss", members: [{_id:0,host:"49.232.165.242:27117"},{_id:1,host:"49.232.165.242:27118"}]})' # 初始化副本集群
  store:
    image: "java:8"
    container_name: store
    restart: always
    ports:
      - 8002:8002
    volumes:
      - /Users/wangchanghao/Desktop/work/onss/picture:/picture
      - /Users/wangchanghao/Desktop/work/onss/web/store/target/store-service-0.0.1-SNAPSHOT.jar:/onss/store-service-0.0.1-SNAPSHOT.jar
    entrypoint: ["java","-jar","/onss/store-service-0.0.1-SNAPSHOT.jar","--spring.profiles.active=docker"]
  shop:
    image: "java:8"
    container_name: shop
    restart: always
    ports:
      - 8001:8001
    volumes:
      - /Users/wangchanghao/Desktop/work/onss/picture:/picture
      - /Users/wangchanghao/Desktop/work/onss/web/shop/target/shop-service-0.0.1-SNAPSHOT.jar:/onss/shop-service-0.0.1-SNAPSHOT.jar
    entrypoint: ["java","-jar","/onss/shop-service-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=docker"]
  mysql-db:
    container_name: mysql        # 指定容器的名称
    image: 'mysql:5.7.32'                  # 指定镜像和版本
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456