spring:
  data:
    mongodb:
      uri: mongodb://49.232.165.242:27017/test?replicaSet=onss
  main:
    lazy-initialization: true
logging:
  level:
    root: info
  file:
    path: var/log
system:
  file-path: picture