server:
  port: 8001
  servlet:
    context-path: /shop
    encoding:
      force-response: true
logging:
  level:
    root: info
  file:
    path: log/shop
spring:
  profiles:
    active: develop
wechat:
  appid: wxb7dc92a3570afc3e
  key: 78a64d9313cc7e93fcddc3de90139d39
  mchid: 1573972751
  serialno: 155B5E15AF0B644879126A37A8E2C878A1A048FC
  keys: {
    wx095ba1a3f9396476: '7692f5acd04248d1ac84c55799c4bc9b',
    wxe78290c2a5313de3: 'c0874a7afed78170601218d82d9dc1b3'
  }
  notify-url: ''
system:
  logo: 'picture/logo2.png'
  public-key-str: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgDi5IbifNfGmyqnR36CZRG+n29Ff4YnC72I3a4Om52Hl9IWvBD8jFbT2qgKM3U7rK/BtzXPGB/tChEq3f0/8b3SPr42tL3aj7KrJixqX+h5pDJZgQO3dk8WVV4jXYuzYC79oe99jaa4sacaA1xPx+B5E2YO2EHlpcm/hr1nHaePIk5pRC4kUYdg5i5hEmn5cjzWeGYFJGWrMwJGx79ZwEMVWIY4J0bDUN1Xy3PkUpaVa/zfhCj/Q2AMmOcm6OPqLAdmfoym+YkgVXLhwT4V6UMAUR0vqVqoViZBL4rG7gSmcdSMoQDJEcbi8Rkk4yWaw93BTKZQZNTUrQ9KNIkRxpwIDAQAB'
  private-key-str: 'MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCAOLkhuJ818abKqdHfoJlEb6fb0V/hicLvYjdrg6bnYeX0ha8EPyMVtPaqAozdTusr8G3Nc8YH+0KESrd/T/xvdI+vja0vdqPsqsmLGpf6HmkMlmBA7d2TxZVXiNdi7NgLv2h732NprixpxoDXE/H4HkTZg7YQeWlyb+GvWcdp48iTmlELiRRh2DmLmESaflyPNZ4ZgUkZaszAkbHv1nAQxVYhjgnRsNQ3VfLc+RSlpVr/N+EKP9DYAyY5ybo4+osB2Z+jKb5iSBVcuHBPhXpQwBRHS+pWqhWJkEvisbuBKZx1IyhAMkRxuLxGSTjJZrD3cFMplBk1NStD0o0iRHGnAgMBAAECggEAGlAJpeLmQUKy8LoCyLqDWWj0cIa5/2Wu7EMijly4/pi3gQOCFAQE5ip5yA+36p6MYjr3vYa5p9+nGdDfcS/v5MttxR/0312gbCvsKjCt6XUeJ6ggXpKxuuZ8LDd3w+RIvbhs76a7Fu/YS2ih/gEo0bscc+q0jRLtUb+l978bzh3WEji+5X0pkzCGHC7yWU0pEd9KZaqtZN86yNNVwCyOIJ2Tpl4PJRtCd87nBuV1iYCeRPN6z9laHNkAHSP2kw5M5LwYXI1jOnsY4NcIlLlxS/VSGoq6VmZDJEI67rLyhmrut0cMZ5BYKstwT91Fw05/dOVpJtRcAJXNy/EpdnF9eQKBgQDXCF+/9+7X3IgGQKkp0zcpZBbR/PcC2Mlzo0zisIl/ref9Z9g7vU/KdC6hzLtjTQGN+prqtz4HYEhbYybn9DqJgHYY8vZvsGhI2jKD3Nr7Pi86eI9OiHr5BmJn48baNliufh8KCtgaogUPI25wbKP8uRVHyC4jOumQr8ZW7R11PQKBgQCYpmBA5bBy6my1ek+LTtDVf0kgMHfd1fJslgE0rKZqjHsB47AHFf1D81yi766eT+Zewdf0rlVLL8Gz5hJj4o0vCUKJb56v8k0SPFy+QUBDKYKXrttGrdUVzV6/3nJAdayIRtCT3s4vnURW3UVikmVXsENJu+/8ZL31Q+ljpsDYswKBgQCR6c3HXv9EnRH0ZDYl+nxI6vENRwF6fg6dGGeYv8Bd0m1EqA2z4+9b6uClzF4vsNZoOHCc6wD9UllnIe4JodGC8pewsFWHToZFQULb9abmq7iyjZJ48OW5S5rE8mxCMHSW22BGmTsxP1X9gsZzJVVVrWYCUpT0NQq+snf9DmNZ5QKBgQCWEIFxaxwCbJi/82S9U5cTO1V9EojUCR6QRwsaaFwVRNMsMVR8Ms7O/TBlcXDdazjSkIenn7Zz+pfXLeeIUFBxHA5QI+4BlBbWRYb69hShse4TBa/FFOD01Pc/cgQpgEVDlzI3HALgZh+nsVEjrT15betIUjyDh9oCgmevMmBE5wKBgQCUVD+azDQIJfjzOJDpxyXyAIptmhB3JBpqnqKaABNxi5Z0/AO4A1qknLzE25RQp2FjlYFSPbCjZMgyIRnTFw4hJQourbfTYyVpxWF7OAadSs4n+sOL+c8mojTLvXkJcabUvAb5gk6gp64suT/6DiiQl0ag9unj3aDuIEhEfofdeA=='
  banks: [
    '工商银行',
    '交通银行',
    '招商银行',
    '民生银行',
    '中信银行',
    '浦发银行',
    '兴业银行',
    '光大银行',
    '广发银行',
    '平安银行',
    '北京银行',
    '华夏银行',
    '农业银行',
    '建设银行',
    '邮政储蓄银行',
    '中国银行',
    '宁波银行',
    '其他银行' ]
  subject-types: {
    SUBJECT_TYPE_INDIVIDUAL: [
      '餐饮',
      '食品生鲜',
      '私立/民营医院/诊所',
      '保健器械/医疗器械/非处方药品',
      '游艺厅/KTV/网吧',
      '机票/机票代理',
      '宠物医院',
      '培训机构',
      '零售批发/生活娱乐/其他',
      '话费通讯',
      '门户论坛/网络广告及推广/软件开发/其他',
      '游戏',
      '加油'],
    SUBJECT_TYPE_ENTERPRISE: [
      '餐饮',
      '食品生鲜',
      '私立/民营医院/诊所',
      '保健器械/医疗器械/非处方药品',
      '游艺厅/KTV/网吧',
      '机票/机票代理',
      '宠物医院',
      '培训机构',
      '零售批发/生活娱乐/其他',
      '电信运营商/宽带收费',
      '旅行社',
      '宗教组织',
      '房地产/房产中介',
      '共享服务',
      '文物经营/文物复制品销售',
      '拍卖典当',
      '保险业务',
      '众筹',
      '财经/股票类资讯',
      '话费通讯',
      '婚介平台/就业信息平台/其他',
      '在线图书/视频/音乐/网络直播',
      '游戏',
      '门户论坛/网络广告及推广/软件开发/其他',
      '物流/快递',
      '加油',
      '民办中小学及幼儿园',
      '公共事业（水电煤气）',
      '信用还款',
      '民办大学及院校'],
    SUBJECT_TYPE_INSTITUTIONS: [
      '其他缴费',
      '公共事业（水电煤气）',
      '交通罚款', '公立医院',
      '公立学校',
      '挂号平台'],
    SUBJECT_TYPE_OTHERS: [
      '宗教组织',
      '机票/机票代理',
      '私立/民营医院/诊所',
      '咨询/娱乐票务/其他',
      '民办中小学及幼儿园',
      '民办大学及院校',
      '公益'],
  }
  file-path: picture/